---
# tasks file for etc_host

- name: if running on laptop, add an alias for Callisto, dataverse etc.
  lineinfile:
     path: "/etc/hosts"
     line: "127.0.0.1 www.{{callisto_url}} {{callisto_url}} dataverse.{{callisto_url}}"
     state: present
  when: callisto_living_on == "laptop"

