---
# tasks file for proxy
- name: launching rewrite module
  apache2_module:
     name: "rewrite"
     state: present
  notify: restart apache

- name: installing configuration file for dataverse
  template:
     src:  dataverse.conf
     dest: /etc/httpd/conf.d/dataverse.conf
     owner: root
     group: root
     mode: '0644'
     backup: yes
  notify: restart apache

- name: laptop, creating mockShib directory
  file:
    path: /etc/http.d/conf.d/mockShib
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ansible_host == "CallistoProxy" and callisto_living_on == "laptop"

- name: installing configuration file for portal
  template:
     src:  portal.conf
     dest: /etc/httpd/conf.d/portal.conf
     owner: root
     group: root
     mode: '0644'
     backup: yes
  notify: restart apache

