---
# tasks file for proxy
- name: launching rewrite module
  apache2_module:
     name: "rewrite"
     state: present
  notify: restart apache

- name: Uploading certificates
  copy:
     src:  ssl
     dest: /etc/httpd
     owner: root
     group: root
     mode: '0644'
     backup: no 
  notify: restart apache

- name: protecting key
  file:
    path: /etc/httpd/ssl/key.pem
    state: file
    owner: root
    group: root
    mode: '0400'
  notify: restart apache

- name: installing the certificate for the generic ssl.conf file (1/3)
  lineinfile:
     path: "/etc/httpd/conf.d/ssl.conf"
     regexp: "^SSLCertificateFile "
     line: "SSLCertificateFile /etc/httpd/ssl/cert.pem"
     state: present
  when: callisto_living_on == "server"

- name: installing the certificate for the generic ssl.conf file (2/3)
  lineinfile:
     path: "/etc/httpd/conf.d/ssl.conf"
     regexp: "^SSLCertificateKeyFile "
     line: "SSLCertificateKeyFile /etc/httpd/ssl/key.pem"
     state: present
  when: callisto_living_on == "server"

- name: installing the certificate for the generic ssl.conf file (3/3)
  lineinfile:
     path: "/etc/httpd/conf.d/ssl.conf"
     regexp: "^SSLCACertificateFile "
     line: "SSLCACertificateFile /etc/httpd/ssl/chain.pem"
     state: present
  when: callisto_living_on == "server"

- name: installing configuration file for dataverse
  template:
     src:  dataverse.conf
     dest: /etc/httpd/conf.d/dataverse.conf
     owner: root
     group: root
     mode: '0644'
     backup: yes
  notify: restart apache

- name: on laptop, mocking shibboleth
  copy:
     src: mockShib
     dest: /etc/httpd/conf.d
     owner: root
     group: root
     mode: '0644'
     backup: no
  notify: restart apache
  when: callisto_living_on == "laptop"

- name: on server, adding shibboleth repository
  yum_repository:
    name:        shibboleth
    description: Shibboleth YUM repo
    state:       present
    mirrorlist:  https://shibboleth.net/cgi-bin/mirrorlist.cgi/CentOS_7
    gpgcheck:    yes
    gpgkey:      https://shibboleth.net/downloads/service-provider/RPMS/repomd.xml.key
  when: callisto_living_on == "server"

- name: on server, installing shibboleth
  yum:
    name:
       - shibboleth
    update_cache: true
    state: latest
  when: callisto_living_on == "server"
  notify:
    - restart shibd
    - restart apache

- name: On server, ensure shibd is running and enabled
  service: name=shibd state=started enabled=yes
  when: callisto_living_on == "server"

# See http://guides.dataverse.org/en/latest/installation/shibboleth.html
- name: on server, configuring shibboleth (1/3)
  copy:
     src: attribute-map.xml 
     dest: /etc/shibboleth
     owner: root
     group: root
     mode: '0644'
     backup: no
  notify: restart shibd
  when: callisto_living_on == "server"

# See https://services.renater.fr/federation/documentation/guides-installation/sp3/chap05
- name: on server, configuring shibboleth (2/3)
  template:
     src: shibboleth2.xml
     dest: /etc/shibboleth/shibboleth2.xml
     owner: root
     group: root
     mode: '0644'
     backup: no
  notify: restart shibd
  when: callisto_living_on == "server"

- name: on server, configuring shibboleth (3/3)
  copy:
     src: "{{ shibd_metadata_cert }}"
     dest: /etc/shibboleth/{{ shibd_metadata_cert }}
     owner: root
     group: root
     mode: '0644'
     backup: no
  notify: restart shibd
  when: callisto_living_on == "server"

- name: installing configuration files
  template:
     src:  "{{item}}"
     dest: /etc/httpd/conf.d/{{item}}
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - portal.conf
     - dataverse.conf
     - allegro.conf 
  notify: restart apache

