---
# tasks file for proxy
- name: installing configuration file for dataverse
  template:
     src:  dataverse.conf
     dest: /etc/httpd/conf.d/dataverse.conf
     owner: root
     group: root
     mode: '0644'
     backup: yes
  notify: restart apache

  #- name: on laptop, creating mockShib directory
  #file:
  #  path: /etc/httpd/conf.d/mockShib
  #  state: directory
  #  owner: root
  #  group: root
  #  mode: '0755'
  #when: ansible_host == "CallistoProxy" and callisto_living_on == "laptop"

- #name: on laptop, creating dummy file h.conf
  #file:
  #  path: /etc/httpd/conf.d/mockShib/h.conf
  #  state: touch
  #  owner: root
  #  group: root
  #  mode: '0755'
  #when: ansible_host == "CallistoProxy" and callisto_living_on == "laptop"
  #notify: restart apache

- name: on laptop, mocking shibboleth
  copy:
     src: mockShib
     dest: /etc/httpd/conf.d
     owner: root
     group: root
     mode: '0644'
     backup: no
  notify: restart apache

- name: Installing certificates
  copy:
     src:  ssl
     dest: /etc/httpd
     owner: root
     group: root
     mode: '0644'
     backup: no 
  notify: restart apache

- name: protecting key
  file:
    path: /etc/httpd/ssl/key.pem
    state: file
    owner: root
    group: root
    mode: '0400'
  notify: restart apache
    
- name: launching rewrite module
  apache2_module:
     name: "rewrite"
     state: present
  notify: restart apache

- name: installing configuration files
  template:
     src:  "{{item}}"
     dest: /etc/httpd/conf.d/{{item}}
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - portal.conf
     - dataverse.conf
     - allegro.conf 
  notify: restart apache

