---
#
# This file is part of Callisto software
# Callisto helps scientists to share data between collaborators
#
# Callisto is free software: you can redistribute it and/or modify
# it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#  Copyright (C) 2019-2021    C A L M I P
#  callisto is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU AFFERO GENERAL PUBLIC LICENSE for more details.
#
#  You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
#  along with Callisto.  If not, see <http://www.gnu.org/licenses/agpl-3.0.txt>.
#
#  Authors:
#        Thierry Louge      - C.N.R.S. - UMS 3667 - CALMIP
#        Emmanuel Courcelle - C.N.R.S. - UMS 3667 - CALMIP
#

# tasks file for portal

- name: Installing php on the portal only
  yum:
    name:
       - php
    state: latest
  notify: restart apache

- name: Configuring php (display_errors On on laptop)
  lineinfile:
     path: "/etc/php.ini"
     regexp: "^display_errors *="
     line: "display_errors = On"
     state: present
  notify: restart apache
  when: callisto_living_on == "laptop" 

- name: Installing several python packages using pip
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pip:
    name:
      - agraph-python
      - six 
      - rdflib
      - jellyfish
      - scipy
      - pandas
      - matplotlib
    executable: pip3

- name: Add the user 'callisto'
  user:
    name: callisto
    comment: 

- name: installing configuration file
  template:
     src:  00-portal.conf
     dest: /etc/httpd/conf.d
     owner: root
     group: root
     mode: '0644'
     backup: yes
  notify: restart apache

- name: installing assets directory and other files
  copy:
     src:  callisto/{{ item }}
     dest: /var/www/html/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - assets
     - css
     - js
  when: send_all_files == true 

- name: installing login/logout for laptop installation only
  copy:
     src:  callisto/{{ item }}
     dest: /var/www/html/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - login
     - logout
  when: callisto_living_on == "laptop"

- name: installing non-template web portal elements
  copy:
     src:  callisto/html/{{ item }}
     dest: /var/www/html/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - work.html

- name: installing demonstration repository file 
  template:
     src:  UTILS/{{ item }}
     dest: /home/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - demonstration.nt
     
- name: installing callisto management scripts
  template:
     src:  UTILS/{{ item }}
     dest: /usr/local/bin
     owner: root
     group: root
     mode: '0755'
     backup: yes
  loop:
     - DataSetsToAllegro.py
     - GenerateDataverseMetadata.py
     - RegisterPublication.py
     - RegisterService.py
     - Update_Allegro_Repositories.py
     - initialize_demonstration_repository.py

- name: installing web site
  template:
     src:  callisto/{{ item }}
     dest: /var/www/html/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - index.php
     - index-dataverse.php
     - menu.inc
     - headers.inc
     - index-tools.php
     - index-work.php
     - collaborate.html
     - index-contact.php
     - tools.html
     - contact.html
     - license.txt

- name: installing javascript
  template:
     src:  callisto/js/{{ item }}
     dest: /var/www/html/callisto/js
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - FctsAllegro.js

- name: creating TempFiles directory
  file:
    path: /var/www/html/callisto/TempFiles
    state: directory
    owner: apache
    group: root
    mode: '0740'

- name: installing cgi-bin
  template:
     src:  cgi-bin/{{ item }}
     dest: /var/www/cgi-bin
     owner: root
     group: root
     mode: '0755'
     backup: yes
  loop:
     - Allegro_Fcts.py
     - Constants.py
     - display.py
     - get_dataset.py
     - mean_Cp.py
     - mean_Cp_source.py
     - psd_display.py
     - psd_fft_display.py
     - psd_fft.py
     - psd_fft_source.py
     - psd_periodogram.py
     - psd_periodogram_source.py
     - psd_welch.py
     - psd_welch_source.py
     - StringDist.py
     - cgi_conf.cfg

- name: creating cgi-bin TempFiles directory
  file:
    path: /var/www/cgi-bin/TempFiles
    state: directory
    owner: apache
    group: root
    mode: '0740'

- name: creating /var/log/callisto directory
  file:
    path: /var/log/callisto
    state: directory
    owner: apache
    group: root
    mode: '0740'

- name: synchronize dataverse and allegro every 15mn
  cron:
    name: "sync dataverse<->allegro"
    minute: "9,19,29,39,49,59"
    hour: "7-23"
    job: "/usr/local/bin/Update_Allegro_Repositories.py > /dev/null"

- name: clean TempFiles (cgi-bin)
  cron:
    name: "Clean cgi-bin TempFiles"
    minute: "23"
    hour: "7-23"
    job: find /var/www/cgi-bin/TempFiles -type f -ctime +1 | xargs rm -rf > /dev/null

- name: clean TempFiles (var/www)
  cron:
    name: "Clean var/www TempFiles"
    minute: "27"
    hour: "7-23"
    job: find /var/www/html/callisto/TempFiles -type f -ctime +1 | xargs rm -rf > /dev/null

