---
# tasks file for portal
- name: installing configuration file
  copy:
     src:  00-callisto.conf
     dest: /etc/httpd/conf.d
     owner: root
     group: root
     mode: '0644'
     backup: yes
  notify: restart apache

- name: installing assets directory and other files
  copy:
     src:  callisto/{{ item }}
     dest: /var/www/html/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - assets
     - css
     - js
  when: send_all_files == true 

- name: installing web site
  template:
     src:  callisto-{{ callisto_living_on }}/{{ item }}
     dest: /var/www/html/callisto
     owner: root
     group: root
     mode: '0644'
     backup: yes
  loop:
     - index.php
     - index-dataverse.php
     - menu.php
     - tools.html
     - work.html
     - collaborate.html
     - contact.php
     - license.txt

- name: creating TempFiles directory
  file:
    path: /var/www/html/callisto/TempFiles
    state: directory
    owner: root
    group: root
    mode: '0777'
  when: ansible_host == "CallistoPortal"



