---
# tasks file for create_containers

- name: if running on laptop, add an alias for Callisto, dataverse etc.
  delegate_to: localhost
  connection: local
  lineinfile:
     path: "/etc/hosts"
     line: "127.0.0.1 www.{{callisto_url}} {{callisto_url}} dataverse.{{callisto_url}}"
     state: present
  when: callisto_living_on == "laptop"

- name: containers exist
  delegate_to: localhost
  connection: local
  lxd_container:
     url: https://127.0.0.1:8443
     ephemeral: no
     source:
         type: image
         mode: pull
         server: https://images.linuxcontainers.org
         protocol: lxd # if you get a 404, try setting protocol: simplestreams
         alias: centos/7/amd64
     name: "{{ inventory_hostname }}"
     architecture: x86_64
     state: started
  notify:
    - attach port80
    - attach port443

     #- name: Declaring CallistoProxy as an http proxy (port 443)
     #delegate_to: localhost
     # connection: local
     # shell: lxc config device get CallistoProxy callport443 name 2>/dev/null || lxc config device add CallistoProxy callport443 proxy listen=tcp:0.0.0.0:443 connect=tcp:127.0.0.1:443 proxy_protocol=true

  #- 
  #debug:
  #  var: ansible_host

      #- name: Declaring CallistoProxy as an http proxy (port 80)
      #delegate_to: localhost
      #connection: local
      #shell: lxc config device get CallistoProxy callport80 name 2>/dev/null || lxc config device add CallistoProxy callport80 proxy listen=tcp:0.0.0.0:80 connect=tcp:127.0.0.1:80 proxy_protocol=true
      #when: ansible_host == "CallistoProxy"

      #- name: network configuration
      #delegate_to: localhost
      #shell: 
      #cmd: bash network-configuration.bash
      #creates: NETWORK-OK

- name: Set the timezone to {{ callisto_timezone }}
  timezone:
     name: "{{ callisto_timezone }}"

     #- name: from the inventory, edit the /etc/hosts file
     #  lineinfile:
     #path: "/etc/hosts"
     #regexp: ".+{{ item }}"
     #line: "{{ hostvars[item]['container_addr'] }} {{ item }}"
     #state: present
     #backup: true
     #loop: "{{ groups['all'] }}"

- name: Installing required software
  yum:
    name:
       - httpd
       - vim
       - epel-release
    update_cache: true
    state: latest

- name: Ensure apache is running
  service: name=httpd state=started enabled=yes

- name: Installing mod_ssl
  yum:
    name:
       - mod_ssl
    state: latest
  notify: restart apache

- name: Installing php on the portal only
  yum:
    name:
       - php
    state: latest
  notify: restart apache
  when: inventory_hostname == "CallistoPortal"

- name: Install ssh and firefox in containers
  yum:
    name:
      - openssh-server
      - xauth
      - firefox
    state: latest
  when: ssh_wanted == true
  
- name: Ensure sshd is running
  service: name=sshd state=started enabled=yes

- name: Create the root .ssh directory
  file:
    dest: "/root/.ssh"
    state: directory
    group: root
    owner: root
    mode: '0700'
  when: ssh_wanted == true

- name: Send my ssh key to the new container
  copy:
    src: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"
    dest: .ssh/authorized_keys
    group: root
    owner: root
    mode: '0600'
  when: ssh_wanted == true

- name: Installing some stuff recommended for server administration
  yum:
    name:
       - ssmtp
       - yum-cron
       - logwatch
    state: latest
  when: callisto_living_on == "server"

- name: Configuring ssmtp -> ssmtp.conf
  template:
     src: ssmtp.conf
     dest: /etc/ssmtp/ssmtp.conf
     owner: root
     group: root
     mode: '0644'
     backup: yes
  when: callisto_living_on == "server"

- name: Configuring ssmtp -> revaliases
  template:
     src: revaliases
     dest: /etc/ssmtp/revaliases
     owner: root
     group: mail
     mode: '0640'
     backup: yes
  when: callisto_living_on == "server"

- name: Configuring yum-cron -> yum-cron.conf
  template:
     src: yum-cron.conf
     dest: /etc/yum/yum-cron.conf
     owner: root
     group: root
     mode: u=rx,go=r
     backup: yes
  when: callisto_living_on == "server"

- name: Configuring logwatch -> logwatch.conf
  template:
     src: logwatch.conf
     dest: /etc/logwatch/logwatch.conf
     owner: root
     group: root
     mode: u=rx,go=r
     backup: yes
  when: callisto_living_on == "server"

- name: Configuring logwatch -> weekly, not daily
  command:  
     removes: /etc/cron.daily/0logwatch
     creates: /etc/cron.weekly/0logwatch
     cmd: mv /etc/cron.daily/0logwatch /etc/cron.weekly
  when: callisto_living_on == "server"

